'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Building2, MapPin, ArrowRight, Clock, Trash2 } from 'lucide-react';
import { StatusBadge } from '@/components/shared/status-badge';
import { getCurrentLifecycleLabel, getCurrentWorkflowStage, getPipelineProgress } from '@/lib/pipeline';
import type { PipelineJob } from '@/types';
import { cn } from '@/lib/utils';
import { formatDistanceToNow } from 'date-fns';

export function JobCard({ job }: { job: PipelineJob }) {
  const router = useRouter(); const [isDeleting, setIsDeleting] = useState(false); const progress = getPipelineProgress(job.pipeline_stage); const workflowStage = getCurrentWorkflowStage(job.application_stage); const href = workflowStage?.href(job.id) ?? `/jobs/${job.id}`;
  async function handleDelete(event: React.MouseEvent<HTMLButtonElement>) { event.preventDefault(); event.stopPropagation(); if (!window.confirm(`Delete ${job.title} at ${job.company}?`)) return; setIsDeleting(true); try { await fetch(`/api/jobs/${job.id}`, { method: 'DELETE' }); router.refresh(); } finally { setIsDeleting(false); } }
  return <Link href={href} className="group block rounded-2xl border border-border bg-card p-4 transition-all duration-200 hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl hover:shadow-primary/10"><div className="mb-3 flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="mb-2 flex items-center gap-2"><StatusBadge stage={job.pipeline_stage} fallbackLabel={getCurrentLifecycleLabel(job)} /></div><h3 className="text-pretty text-sm font-semibold text-foreground transition-colors group-hover:text-primary">{job.title}</h3></div><button type="button" onClick={handleDelete} disabled={isDeleting} className="inline-flex h-9 w-9 items-center justify-center rounded-xl border border-border text-muted-foreground transition-all hover:border-destructive/30 hover:text-destructive"><Trash2 className="h-4 w-4" /></button></div><div className="mb-3 flex items-center gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Building2 className="h-3.5 w-3.5 shrink-0" /><span className="truncate">{job.company}</span></span>{job.location && <span className="flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5 shrink-0" /><span className="truncate">{job.location}</span></span>}</div><div className="space-y-1.5"><div className="mb-1 flex items-center justify-between gap-2 text-[11px] text-muted-foreground/70"><span>{workflowStage ? `Workflow: ${workflowStage.label}` : getCurrentLifecycleLabel(job)}</span><span>{progress}%</span></div><div className="h-1.5 w-full overflow-hidden rounded-full bg-white/5"><div className={cn('h-full rounded-full transition-all duration-500', progress < 100 ? 'bg-primary/50' : 'bg-primary')} style={{ width: `${Math.max(progress, 4)}%` }} /></div></div><div className="mt-3 flex items-center gap-1.5"><Clock className="h-3 w-3 text-muted-foreground/40" /><span className="text-[11px] text-muted-foreground/50">{formatDistanceToNow(new Date(job.updated_at), { addSuffix: true })}</span>{job.compensation && <span className="ml-auto truncate text-[11px] text-muted-foreground/50">{job.compensation}</span>}</div><div className="mt-3 flex items-center justify-between rounded-xl border border-primary/15 bg-primary/5 px-3 py-2 text-sm font-medium text-foreground"><span>{workflowStage ? 'Continue packet' : 'Open job'}</span><ArrowRight className="h-4 w-4 text-primary" /></div></Link>;
}
